# Generated by Django 3.2.6 on 2021-09-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='Por defecto', max_length=255),
            preserve_default=False,
        ),
    ]
